# Generated by Django 5.2.11 on 2026-02-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Full HTML content of the newsletter"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short summary for the archive list"
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_count",
                    models.IntegerField(
                        default=0, help_text="Number of subscribers this was sent to"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
